### ISSUE TITLE
XL -320 incompatible

### ISSUE THREAD

**Issue by Shotch** [jthorniley/pyusb2ax#2]
The Dynamixel XL-320's are supported via the usb2ax, however I can't seem to get them to connect through this wrapper despite them being found via Robotis's applications.

I'm curious if there would be anyway to add such compatibility and or what would be required to modify to gain compatibility.

**Comment by jthorniley** [comment]
Hi

Its a while since I wrote this so I'm working from memory mainly. I think what you'd need to do is look at usb2ax.pyx in the source, there are a couple of existing dictionaries that look like this:

```
MMAP_MX={
#EEPROM
"model_no":[0x00,2,False],
"firmware_version":[0x02,1,False],
"id":[0x03,1,True],
"baud_rate":[0x04,1,True],
"return_delay_time":[0x05,1,True],
"cw_angle_limit":[0x06,2,True],
"ccw_angle_limit":[0x08,2,True],

"high_limit_temp":[0x0B,1,True],
"low_limit_voltage":[0x0C,1,True],
"high_limit_voltage":[0x0D,1,True],

"max_torque":[0x0E,2,True],
"status_return_level":[0x10,1,True],
"alarm_led":[0x11,1,True],
...
```

What you need to do is create another one, call is `MMAP_XL320` say alongside, and fill it in on the basis of the control map in the manual: http://support.robotis.com/en/product/dynamixel/xl-series/xl-320.htm

From the columns there, take the address (the manual says hexademical, but I'm fairly sure its not, its probably decimal from the looks of things), the number of bytes and whether or note its read-write, then fill in each entry of the table like this:

```
"cw_angle_limit":[6,2,True],
```

Where "cw_angle_limit" is just an internal (to python) name for the parameter - its the name you'd use to write to (doesn't matter in principle what this is, but I'd make it correspond to the existing maps as much as possible for consistency). "6" for address 6, "2" because its 2 bytes, and "True" because its a read-write parameter (would be False for read only).

Youd then need to extend this bit of the code appropriately:

```
            my_map = MMAP_AX
            if model in [12,18]:
                model = "AX-%d   " % model
            elif model == 29:
                model = "MX-%dT  " % model
                my_map = MMAP_MX
            else:
                model = "Model %d" % model
```

At the moment, "my_map" defaults to `MMAP_AX`, and then it changes when the model number is read from the dynamixel on startup to MX if necessary. The model number for the xl-320 according to the manual is 350, so I think what you want is

```
            my_map = MMAP_AX
            if model in [12,18]:
                model = "AX-%d   " % model
            elif model == 29:
                model = "MX-%dT  " % model
                my_map = MMAP_MX
            elif model == 350:
                model = "XL-320  " % model
                my_map = MMAP_XL320
            else:
                model = "Model %d" % model
```

I think that should be enough to make it work but let me know if that doesn't do it.

James

**Comment by Shotch** [comment]
I have made the changes and it still can't see any devices on the bus, I have confirmed again afterwards that they are properly connected, and are shown when viewed through RoboPlus.

The control mappings were surprisingly similar.

I tried it both with the addresses in decimal, and in hexadecimal to no avail.

**Comment by Shotch** [comment]
After checking the wiring, and checking the addresses, and checking code and doing some further testing I have come up blank yet again. I even checked with another library that is supposedly able to interface with the usb2ax module, however that library was quite messy, and once I managed to make changes and get it running at all, I got communication errors with the servos as well.

Is there any idea you may have of what could be wrong? Simply moving the usb cable from the RPI to my PC and then checking the connection to the servos with RoboPlus, it does show that they are connected, and I am able to communicate to them. It would really like to be able to get this working, and am willing to try almost anything at this point.

**Comment by Sharpyuk** [comment]
Are the servos powered from a separate supply? I suspect USB won't have
enough power

**Comment by Shotch** [comment]
Yes, I have an external power source for the servos. They are non-operable without it, which I know about, and without, I wouldn't be able to connect to RoboPlus. I know the setup is functional on windows, via RoboPlus, but I am unable to get communication to the servos on a Raspberry Pi, with the exact same setup, simply just moving the usb extension cable from my PC to the Pi, with the usb2ax attached at the end.

**Comment by Shotch** [comment]
So, I loaded up an Arduino Uno to just vomit anything sent through one of the digital pins into the usb serial on it. I then plugged in the usb2ax dongle's data pin into that spot on the Uno. I then ran a comparison between what Windows does when I run RoboPlus, and when I try to run a very simple snippet of code from my Raspberry Pi.

I just... I really want this to work, and I can't seem to get anything working with the usb2ax, and I can't even really find any assistance trying to get this thing to work because either people haven't reported these problems anywhere, or it's just me, and I'm very probably doing something very stupid. I could really use some help, even if you can't fix it, if you could try and point me to someone who might be able to help.

[Album of serial terminal results](http://imgur.com/a/4Gm8X)

**Comment by jthorniley** [comment]
Hi there,

Hardware is always frustratingly slow to debug, but there must be a reason.

Something else that could be added for debugging, around line 323 of usb2ax.pyx we have this:

```
        except ReadError, e:
            #Servo not connected, do nothing
            pass

    if no_devices_connected:
        sys.stderr.write ("usb2ax: WARNING: Cannot see any devices on the bus!\n" )
```

The exception is just "pass"-ed because its assumed that no servo is attached. But i suspect this exception might contain some useful information, so replace `pass` with `import traceback; traceback.print_exc()`

Then perhaps upload the result of that.

James

**Comment by Shotch** [comment]
Every id it tries, it responds with the same message:

> Traceback (most recent call last):
>   File "usb2ax.pyx", line 327, in usb2ax.Controller.**init** (usb2ax.c:3513)
>   File "usb2ax.pyx", line 283, in usb2ax.__read (usb2ax.c:3139)
> ReadError: 6

Figured it would be better to abridge it, than upload a pastebin of that over 200 times.

**Comment by jthorniley** [comment]
A couple of other ideas:

You might be able to see data when you've wired up the Arduino with just `cat /dev/ttyACM0`

Just to confirm, you need to run python setup.py to re-build any changes to usb2ax.pyx - its easy to end up with stale copies of this, get rid of any usb2ax.so you see, then built it with `python setup.py build_ext --inplace` - you should get a new usb2ax.so in the same directory, copy that to wherever you are running python from (to be sure)

**Comment by Shotch** [comment]
Yeah, I was doing that before just to see that the Pi data was going through fine, which it ended up constantly having data being sent through it, I issolated it to being the hdmi port on the Pi, if anything was plugged in, the usb2ax module was constantly getting data down the data line when it shouldn't have.

The arduino setup was the only way I could think of to look at the input from windows as well.

And yes, i've been rebuilding it each time, and replacing the old copies, I've even done fresh installs of python a few times and uninstalled versions I don't need to try to alleviate any extraneous possibilities.

**Comment by jthorniley** [comment]
Ok, so the ReadError 6 at least shows its trying but not talking at all to the dynamixel, so its not a problem with the model ID yet. I think the number comes from the dynamixel.h header file

```
#define COMM_RXTIMEOUT          (6)
```

Which suggests its failing to send anything at all (or its not getting any acknowledgement from the servo).

Maybe you could try the arduino set up to check that you are sending something out of the USB2AX, e.g. you could try a command like this:

```
while true; do echo "foo" > /dev/ttyACM0; done
```

(CTRL-C to stop it) - you should see something through the arduino. Or just running the python script you should see at least something.

Not sure why it wouldn't work, maybe something to do with the rpi configuration, try running as root if its a permission issue. Only other thing might be the baud rate (I thought that was set through the dynamixel library, but I'm not sure, maybe there's some other way. You could try changing it with pyserial and see what happens with an arduino based test).

**Comment by SHotch** [comment]
How would I disable the automatic patching of the Dynamixel sdk?

**Comment by jthorniley** [comment]
At the bottom of setup.py, I would guess just comment out the call to patch_dxl_sdk() should work
james

```
On Friday, 26 August 2016, 16:28, S Hotch <notifications@github.com> wrote:
```

 How would I disable the automatic patching of the Dynamixel sdk?—
